### ISSUE TITLE
Consider always using --force-exclude

### ISSUE THREAD

**Issue by henryiii** [charliermarsh/ruff-pre-commit#19]
If it's true that running in pre-commit always needs `--force-exclude` to work properly, then you can set it as part of the entry, such as:

```yaml
entry: ruff --force-exclude
```

This will then always include this option when running, regardless of what args is set to. Assume ruff is fine if this is passed twice (for backward compatibly with existing user's `args:`), then this is the recommended way to do this (for an example, see https://github.com/pre-commit/mirrors-clang-format/blob/ea59a72ffc9a1ce6b79b02a8076d031aa7ea7805/.pre-commit-hooks.yaml#L4 ).

If it's not the case that this (or any other flag) is always required for pre-commit, then nevermind. :)

**Comment by charliermarsh** [comment]
I think this would be a good change. (Ruff should be fine with receiving that argument twice, and I _think_ users could override it by passing `--no-force-exclude`, but I'd have to double-check.)

**Comment by henryiii** [comment]
Users can also override it by adding `entry: ruff`, technically. :)

**Comment by auscompgeek** [comment]
> Ruff should be fine with receiving that argument twice

FWIW Ruff is definitely not fine with receiving that option twice. I just received a pre-commit.ci autoupdate PR where it fails: https://results.pre-commit.ci/run/github/584046811/1674533685.HvDYs3ClQkqwyoDsCuLJvQ
