### ISSUE TITLE
--fix should be included by default

### ISSUE THREAD

**Issue by WhyNotHugo** [charliermarsh/ruff-pre-commit#24]
Most pre-commit hooks apply any changes that need to be made. The task of actually adding (e.g.: `git add`) is left to the user.

It would be a good fit for this hook to do the same; since after running the hooks one can check the changes and act upon them (rather than requiring that one re-runs `ruff` manually).

**Comment by eggplants** [comment]
I suggest to keep `ruff` and  add `ruff-fix`.

Example:
https://github.com/igorshubovych/markdownlint-cli
https://github.com/sqlfluff/sqlfluff

**Comment by WhyNotHugo** [comment]
Even the pre-commit hooks that are part of pre-commit prefer fixing by default:

https://github.com/pre-commit/pre-commit-hooks

Black does this too:

https://github.com/psf/black

Honestly, I don't see the point of not-fixing; you're just adding an extra step to the end user.

**Comment by eggplants** [comment]
But #25 changes `ruff` behavior and affects existing pre-commit configurations. I don't like it.

@charliermarsh, please tell your opinion.

**Comment by WhyNotHugo** [comment]
It does not affect existing configurations. Existing configurations are pinned to a previous version. The change would only apply for those upgrading to a new version.

**Comment by charliermarsh** [comment]
Yeah I appreciate that this PR but I'd rather add `ruff-fix` if we change it at all. I want autofix to remain an opt-in behavior.

**Comment by charliermarsh** [comment]
IMO it's different for Black, where fixing is its primary responsibility, whereas with Ruff, it's reasonable to use it without autofix at all.

**Comment by charliermarsh** [comment]
I guess with `ruff-fix`, I wonder if that's actually even more convenient for users, vs. just adding the `--fix` flag 🤔

**Comment by WhyNotHugo** [comment]
Maybe it's enough to put `--fix` in the README example?

**Comment by WhyNotHugo** [comment]
That way copy-pasting the example results in behaviour similar to other linters, but it's clear to users that they can just avoid including that arg to opt-out of fixing.

**Comment by rr-tomas-henriquez** [comment]
I believe just an example is good enough honestly :)
