### ISSUE TITLE
Hook ID comment from pre-commit maintainer

### ISSUE THREAD

**Issue by tgross35** [charliermarsh/ruff-pre-commit#3]
I suggested adding ruff's hook to the [official supported hooks list](https://pre-commit.com/hooks.html), the maintainer mentioned that hook ID should be something identifying to the project (like `ruff`). I think this is to avoid conflicts when specifying which hook ID to run (`pre-commit run -a lint` would potentially conflict with other linters otherwise)

What are your thoughts here @charliermarsh? It would probably be easy enough to add an identical `ruff` hook, and update the `lint` description to say that option is deprecated.

Link to discussion: https://github.com/pre-commit/pre-commit.com/pull/737

**Comment by charliermarsh** [comment]
Ah good call. I’ll fix this soon (maybe today, if not, then tomorrow).

**Comment by charliermarsh** [comment]
PR also welcome if you're interested. We could even remove the `lint` option entirely and just do `ruff` for all future versions.
