### ISSUE TITLE
.pyi is not currently supported

### ISSUE THREAD

**Issue by touilleMan** [charliermarsh/ruff-pre-commit#8]
See what is done in [black's pre-commit hook](https://github.com/psf/black/blob/d4a85643a465f5fae2113d07d22d021d4af4795a/.pre-commit-hooks.yaml#L8)

tl;dr: `types: [python]` should be replaced by `types_or: [python, pyi]` (:warning: [`types`'s list is AND, where `types_or` is OR](https://pre-commit.com/#config-types_or))

**Comment by charliermarsh** [comment]
Great idea.
